FROM mysql:5.6

# set default values for Database name, user and passwords

ENV MYSQL_ROOT_PASSWORD=password

ENV MYSQL_USER=random_user

ENV MYSQL_PASSWORD=random_password

ENV MYSQL_DATABASE=rand_numbers
