apiVersion: v1
kind: ConfigMap
metadata:
  name: random-config-env
  creationTimestamp: 2019-04-13T13:31:07+00:00
  namespace: default
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://database-svc:3306/rand_numbers
  STAT_URL: http://random-statistic-svc:8080/
  RAND_NUM_URL: http://middle-tier-svc:7070/
  HISTORY_URL: http://random-statistic-svc:8080/history/
  RANDOM_GENERATOR_URL: http://random-generator-svc:5050/

  
