apiVersion: v1
kind: Service
metadata:
  name: database-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: database
  clusterIP: None
  ports:
  - port: 3306
        
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: rand-gen
    location: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-gen
      location: database
  template:
    metadata:
      labels:
        app: rand-gen
        location: database
    spec:
      containers:
      - name: database
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rand-secret-file
                key: rootpassword.txt
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: rand-secret-file
                key: username.txt
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rand-secret-file
                key: password.txt
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: random-config-env
                key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
