apiVersion: v1
kind: Service
metadata:
  name: database-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: database
  clusterIP: None
  ports:
  - port: 3306
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: rand-gen
    location: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-gen
      location: database
  template:
    metadata:
      labels:
        app: rand-gen
        location: database
    spec:
      containers:
      - name: database-container
        image: toky03/rand-database:1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rand-secret
              key: databaseRootPassword
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: rand-secret
              key: databaseUsername
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rand-secret
              key: databasePassword
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
               name: random-config
               key: database.name
        ports:
        - containerPort: 3306
