apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: frontend
  type: NodePort # make the service accessible from outside
  ports:
  - protocol: TCP
    port: 5123
    targetPort: 8080
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: rand-gen
    location: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-gen
      location: frontend
  template:
    metadata:
      labels:
        app: rand-gen
        location: frontend
    spec:
      containers:
      - name: frontend-container
        image: toky03/rand-front-image:1.0
        envFrom:
        - configMapRef:
            name: random-config-env
        ports:
        - containerPort: 8080
