apiVersion: v1
kind: Service
metadata:
  name: random-generator-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: generator
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-deployment
  labels:
    app: rand-gen
    location: generator
spec:
  replicas: 2 # to showcase diffrent generator ids
  selector:
    matchLabels:
      app: rand-gen
      location: generator
  template:
    metadata:
      labels:
        app: rand-gen
        location: generator
    spec:
      containers:
      - name: random-generator-container
        image: toky03/rand-gen-image:1.0
        ports:
        - containerPort: 5050
