apiVersion: v1
kind: Service
metadata:
  name: middle-tier-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: backend
  type: NodePort
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
    nodePort: 31234
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle-tier-controller
  labels:
    app: rand-gen
    location: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-gen
      location: backend
  template:
    metadata:
      labels:
        app: rand-gen
        location: backend
    spec:
      containers:
      - name: random-controller-container
        image: random-controller-image
        imagePullPolicy: Never
        ports:
        - containerPort: 7070
