apiVersion: v1
kind: Service
metadata:
  name: middle-tier-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: middle
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle-tier-controller
  labels:
    app: rand-gen
    location: middle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-gen
      location: middle
  template:
    metadata:
      labels:
        app: rand-gen
        location: middle
    spec:
      containers:
      - name: random-controller-container
        image: toky03/rand-middle-image:1.0
        envFrom:
        - configMapRef:
            name: random-config-env
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: rand-secret
              key: databaseUsername
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rand-secret
              key: databasePassword
        ports:
        - containerPort: 7070
