apiVersion: v1
kind: Service
metadata:
  name: random-generator-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: backend
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-deployment
  labels:
    app: rand-gen
    location: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rand-gen
      location: backend
  template:
    metadata:
      labels:
        app: rand-gen
        location: backend
    spec:
      containers:
      - name: random-generator-container
        image: random-generator-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
