apiVersion: v1
kind: Service
metadata:
  name: random-statistic-svc
  labels:
    app: rand-gen
spec:
  selector:
    app: rand-gen
    location: stat
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-statistic-deployment
  labels:
    app: rand-gen
    location: stat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-gen
      location: stat
  template:
    metadata:
      labels:
        app: rand-gen
        location: stat
    spec:
      containers:
      - name: random-statistic-container
        image: toky03/rand-stat-image:1.0
        envFrom:
        - configMapRef:
            name: random-config-env
        ports:
        - containerPort: 8080
